version: "2.4"

services:
  odoo:
    build:
      context: ./odoo
      args:
        ODOO_VERSION: "10.0"
        UID: "${UID:-1000}"
        GID: "${GID:-1000}"
    environment:
      EMAIL_FROM: ""
      PGDATABASE: &dbname prod
      PGUSER: &dbuser "odoo"
      PROXY_MODE: "false"
      LIST_DB: "true"
    tty: true
    volumes:
      - filestore_openupgrade:/var/lib/odoo:z

  smtpfake:
    image: docker.io/mailhog/mailhog
